### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Ademola101**
This feature branch creates the four sections of the page. Header, footer, highlight and latest funding sections were created respectively.
The four sections were designed to be responsive to different screen sizes such as mobile devices, tablet devices and desktop devices using media query at different breakpoints.
Layout techniques used includes floating, flexbox. CSS grid, CSS flexbox and positioning.

### CODE REVIEW

**Review by soieducation — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🚦 

### Hello @Ademola101 @YinkTech  and @shadrxcc  :wave: 

### You have done an amazing job on this milestone, your page is looking almost the same as the original, your repository is looking professional and your HTML and CSS are clean. :clap: 

# [Required Changes] :warning: 
- [ ] The main body of the page should have left and right margins
- [ ] The date and author name on the main image are not aligned properly on the desktop screen size
- [ ] Please make adjustments to the footer on the mobile screen size
- [ ] Use similar font style and size for the texts
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

**Review by soieducation — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🚦 

### Hello @Ademola101 @YinkTech  and @shadrxcc  :wave: 

### Great work on implementing the changes required :clap:, however there is still one change to make

# [Required Changes] :warning: 
- [x] Please make adjustments to the footer on the mobile screen size, the footer on the smallest screen(320px) still overflows by the right.

### Please also make sure your commit messages are written in present tense (e.g. add font face for header) and not in past tense (e.g. added font face for header).
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

**Review by soieducation — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @Ademola101 @YinkTech  and @shadrxcc :wave: 

### You have done an amazing job on this milestone, congratulations! Your project is approved :clap: :clap: :clap: 

### Good luck with your next milestones :rocket: 
### Note: always make sure your commit messages are written in present tense (e.g. add font face for header) and not in past tense (e.g. added font face for header).

### Remember to submit your project completion form individually
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

**Comment by Ademola101** [comment]
@soieducation Thank you for the review.

Necessary adjustment noted will be implemented moving on.

**Pull request merged**
