### PR TITLE
Feature 2

### PR DESCRIPTION
**Pull request by shadrxcc**
The feature-2 branch includes the remaining sections of the page.  The Category, Latest News and Latest Deals sections respectively.
These three sections are designed to be responsive on different screen sizes such as mobile devices, tablet devices and desktop devices using media query at different breakpoints. A mobile approach was used first before creating media queries for the other screens (tablet and desktop screens respectively). Great mind was paid to the all the changes in the respective sections at different screen sizes/ breakpoint.
Layout techniques used includes floating, flexbox. CSS grid, CSS flexbox and positioning. We're open to new ideas on how to make this page better!

### CODE REVIEW

**Review by soieducation — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🚦 

### Hello @Ademola101 @YinkTech  and @shadrxcc  :wave: 

### You have done an amazing job on this milestone, your sections are looking almost the same as the original. :clap: 

# [Required Changes] :warning: 
- [ ] The text color, list spacing in the category section should be similar to the original page
Screenshot (187)

- [ ] The latest news boxes should be spaced properly
- [ ] The spacing between boxes in the category and latest deals are not similar to the original page, please fix that
- [ ] Use similar font style and size for the texts
- [ ] Make more use of semantic tags instead of divs
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

**Comment by Ademola101** [comment]
@soieducation Thanks for the review.
I don't understand the suggestion "The latest news boxes should be spaced properly" as I feel it is spaced properly.
Can you clarify?

**Review by soieducation — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @Ademola101 @YinkTech  and @shadrxcc :wave: 

### You have done an amazing job on this milestone, congratulations! Your project is approved :clap: :clap: :clap: 

### Good luck with your next project :rocket: 

### Remember to submit your project completion form individually
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

**Comment by Ademola101** [comment]
@soieducation Thank you for the review and the suggestions

**Pull request merged**
